# Generated by Django 3.2.7 on 2021-10-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avator',
            field=models.ImageField(default='media/avator.png', upload_to='avator'),
        ),
    ]
