# Generated by Django 3.2.7 on 2021-10-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_avator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avator',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/avatar.png', upload_to='avatar'),
        ),
    ]
